#!/bin/sh

WSGIPID="/tmp/uwsgi-twip.pid"
SOCKET="/tmp/uwsgi-twip.sock"
WSGILOG="/tmp/uwsgi-twip.log"

do_start(){
    if test -r $WSGIPID ; then
        echo "Server is already running!"
        exit 0
    fi
    echo -n "Starting uWSGI..."
	uwsgi -s $SOCKET --chmod-socket=666 -M -p 1 --limit-as 512 -R 10000 -d $WSGILOG --pidfile $WSGIPID --module twip --callable app
    echo "[done]"
}
do_stop(){
    if ! test -r $WSGIPID ; then
        echo "Server is not running!"
        exit 0
    fi
    echo -n "Stopping uWSGI..."
	kill -2 `cat -- $WSGIPID`
	rm -f -- $WSGIPID
	rm -f -- $SOCKET
    echo "[done]"
}
show_status(){
    if test -r $WSGIPID ; then
        echo "uWSGI is running."
    else
        echo "uWSGI is not running."
    fi
}

case "$1" in
 start)
     do_start
 ;;
 stop)
     do_stop
 ;;
 restart)
     do_stop
     do_start
 ;;
 status)
     show_status
 ;;
 *)
 echo "Usage: server {start|stop|restart|status}" >&2
 exit 3
 ;;
esac

exit 0
